---
# Configure system users access to MariaDB

- name: Ensure mysql is running
  service: name=mysql state=started

- name: Configure MariaDB root defaults-file
  template: src=root/my.cnf.j2 dest=/root/.my.cnf owner=root group=root mode=0640 force=yes

