---

- include: repository.yml
  tags: repository

- include: packages.yml
  tags: packages

- include: access.yml
- include: config.yml

- name: Ensure permissions are correct
  shell: chown mysql:mysql /var/lib/mysql -R

- shell: galera_new_cluster
  when: galera_bootstrap
  sudo: true

- include: secure.yml

- meta: flush_handlers

