---

- include: repository.yml
  tags: repository

- include: packages.yml
  tags: packages

- include: access.yml
- include: secure.yml
- include: config.yml

- shell: galera_new_cluster
  when: galera_bootstrap
  sudo: true

- meta: flush_handlers

