---
# Setup installation repositories

- name: import repository key
  apt_key: keyserver=keyserver.ubuntu.com id=0xcbcb082a1bb943db

- name: add apt repository
  apt_repository: repo="deb [arch=amd64,i386] http://ams2.mirrors.digitalocean.com/mariadb/repo/10.1/{{ ansible_distribution|lower() }} {{ ansible_distribution_release }} main"
    state=present update_cache=yes
