---
# Secure mysql installation - mysql_secure_installation script analogue

- name: remove test database
  mysql_db:
    name: test
    state: absent

- name: deny remote root access
  mysql_user:
    name: root
    host: "{{ item }}"
  with_items:
    - "localhost"
    - "127.0.0.1"
    - "::1"

- name: deny anonymous access
  mysql_user:
    name: ""
    state: absent

- name: Set MariaDB root password for local login
  mysql_user: name=root password={{ galera_root_password }} host=localhost state=present

- name: Set MariaDB debian-sys-maint password for service control
  mysql_user: name=debian-sys-maint password={{ galera_maintenance_password }} host=localhost state=present