---
# Handlers for MariaDB

- name: restart mysql
  service: name=mysql state=restarted
  serial: 1

- name: start mysql
  service: name=mysql state=started
  serial: 1

- name: stop mysql
  service: name=mysql state=stopped

